# Site settings
title: Allen Madsen
description: Perpetual learner, occasional teacher. Developer, crossfitter, and gamer.
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Allen Madsen
user_description: Perpetual learner, occasional teacher. Developer, crossfitter, and gamer.
email: blatyo@gmail.com
twitter_username: blatyo
github_username:  blatyo
linkedin_username:  allenmadsen

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
